version: '2.0'

services:
  elasticsearch:
      image: elasticsearch:latest
      ports:
        - 9200:9200
      volumes:
        - ./data:/usr/share/elasticsearch/data
      environment:
        ES_JAVA_OPTS: "-Xms1g -Xmx1g"
  kibana:
      image: kibana:latest
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch